package dataaccess.sql;

import chess.ChessGame;
import com.google.gson.Gson;
import dataaccess.DataAccessException;
import dataaccess.DatabaseManager;
import dataaccess.interfaces.GameDAO;
import model.GameData;

import java.sql.*;
import java.util.ArrayList;
import java.util.Collection;

public class SQLGameDAO implements GameDAO {
    private int sqlGameInt = 1;
    private String gameJson = new Gson().toJson(new ChessGame());

/*    @Override
    public int createGame(String gameName) throws DataAccessException {
        sqlGameInt += 1;
        String statement = "INSERT INTO games(gameID, whiteUsername, blackUsername, gameName, game) VALUES (?, ?, ?, ?, ?)";
        try(Connection con = DatabaseManager.getConnection()) {
            PreparedStatement preparedStatement = con.prepareStatement(statement);
            preparedStatement.setInt(1, sqlGameInt);
            preparedStatement.setString(2, null);
            preparedStatement.setString(3, null);
            preparedStatement.setString(4, gameName);
            preparedStatement.setString(5, gameJson);
            preparedStatement.executeUpdate();
            return sqlGameInt;
        } catch (SQLException | DataAccessException e) {
            throw new DataAccessException("Error: " + e.getMessage());
        }
    }*/

    @Override
    public int createGame(String gameName) throws DataAccessException {
        // Note: We no longer include gameID in the columns or values list
        String statement = "INSERT INTO games (whiteUsername, blackUsername, gameName, game) VALUES (?, ?, ?, ?)";

        try (Connection con = DatabaseManager.getConnection();
             PreparedStatement preparedStatement = con.prepareStatement(statement, Statement.RETURN_GENERATED_KEYS)) {

            preparedStatement.setNull(1, java.sql.Types.VARCHAR);
            preparedStatement.setNull(2, java.sql.Types.VARCHAR);
            preparedStatement.setString(3, gameName);
            preparedStatement.setString(4, gameJson);

            preparedStatement.executeUpdate();

            // Retrieve the ID generated by the database
            try (ResultSet generatedKeys = preparedStatement.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    return generatedKeys.getInt(1);
                } else {
                    throw new DataAccessException("Error: Creating game failed, no ID obtained.");
                }
            }
        } catch (SQLException e) {
            throw new DataAccessException("Error: " + e.getMessage());
        }
    }

    @Override
    public GameData getGame(Integer gameID) throws DataAccessException {
        String statement = "SELECT gameID, whiteUsername, blackUsername, gameName, game FROM games WHERE gameID = ?";
        try(Connection connect = DatabaseManager.getConnection()) {
            try(PreparedStatement preparedStatement = connect.prepareStatement(statement)){
                preparedStatement.setInt(1, gameID);
               try(ResultSet rs = preparedStatement.executeQuery()){
                   if (rs.next()){
                       return readGame(rs);
                   }
                   return null;
               }
            }
        } catch (SQLException | DataAccessException e) {
            throw new DataAccessException("Error: " + e.getMessage());
        }
    }

    @Override
    public Collection<GameData> listGames() throws DataAccessException {
        Collection<GameData> endList = new ArrayList<>();
        try(Connection connection = DatabaseManager.getConnection()) {
            String sql = "SELECT gameID, whiteUsername, blackUsername, gameName, game FROM games";
            try(PreparedStatement ps = connection.prepareStatement(sql)){
                try(ResultSet rs = ps.executeQuery()){
                    while (rs.next()){
                        endList.add(readGame(rs));
                    }
                }
            }
        } catch (SQLException | DataAccessException e) {
            throw new DataAccessException("Error: " + e.getMessage());
        }
        return endList;
    }

    @Override
    public void updateGame(GameData g) throws DataAccessException {
        String statement = "UPDATE games SET whiteUsername = ?, blackUsername = ?, gameName = ?, game = ? WHERE gameID = ?";
        try(Connection connection = DatabaseManager.getConnection()) {
            try(PreparedStatement preparedStatement = connection.prepareStatement(statement)){
                preparedStatement.setString(1, g.whiteUsername());
                preparedStatement.setString(2, g.blackUsername());
                preparedStatement.setString(3, g.gameName());
                preparedStatement.setString(4, new Gson().toJson(g.game()));
                preparedStatement.setInt(5, g.gameID());
                preparedStatement.executeUpdate();
            }
        } catch (SQLException | DataAccessException e) {
            throw new DataAccessException("Error: " + e.getMessage());
        }
    }

/*    @Override
    public void clear() throws DataAccessException {
        String sql = "TRUNCATE TABLE games";
        sqlGameInt = 0;
        try(Connection connection = DatabaseManager.getConnection()){
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            preparedStatement.executeUpdate();
        } catch (SQLException | DataAccessException e) {
            throw new DataAccessException("Error: " + e.getMessage());
        }
    }*/

    @Override
    public void clear() throws DataAccessException {
        String sql = "TRUNCATE TABLE games";
        // sqlGameInt = 0; <- REMOVE THIS (DB handles reset if TRUNCATE is used)
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) { // Added to try-with-resources
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            throw new DataAccessException("Error: " + e.getMessage());
        }
    }

    private GameData readGame(ResultSet rs) throws SQLException {
        int gameID = rs.getInt("gameID");
        String whiteUsername = rs.getString("whiteUsername");
        String blackUsername = rs.getString("blackUsername");
        String gameName =rs.getString("gameName");
        var jsonGame = rs.getString("game");
        var chessGame = new Gson().fromJson(jsonGame, chess.ChessGame.class);
        return new GameData(gameID, whiteUsername, blackUsername, gameName, chessGame);

    }
}
